### ISSUE TITLE
表格序号为奇数

### ISSUE THREAD

**Issue by OPgzj** [JWangL5/CAU-ThesisTemplate-Typst#1]
表格序号只会出现奇数
![微信图片_20240512012126](https://github.com/JWangL5/CAU-ThesisTemplate-Typst/assets/101467450/e2a7c592-03ed-4252-98ab-63fbf210936c)

**Comment by JWangL5** [comment]
感谢反馈，图表标题目前确实存在一些问题，还没有严格符合学校的要求（学校要求是[`章节号-图表编号]`这种格式，并且在目录中分开排版）我之后会重新改写一个版本

**Comment by JWangL5** [comment]
@OPgzj 问题是源自于嵌套的`figure()`，可以通过直接使用`booktab()`来添加三线表，新版本的代码适配了booktab的`label`功能，已经修改了README文档
